name: "Hibur Mono"
designer: "Behailu Berento"
license: "OFL"
category: "MONOSPACE"
date_added: "2026-03-08"
fonts {
  name: "Hibur Mono"
  style: "normal"
  weight: 400
  filename: "HiburMono[wght].ttf"
  post_script_name: "HiburMono-Regular"
  full_name: "Hibur Mono Regular"
  copyright: "Copyright 2025-2026 The Hibur Mono Font Project Authors (https://github.com/typehabesha/HiburMono)"
}
subsets: "adlam"
subsets: "cherokee"
subsets: "ethiopic"
subsets: "greek"
subsets: "greek-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "math"
subsets: "menu"
subsets: "tifinagh"
subsets: "yi"
soruce {
  repository_url: "https://github.com/typehabesha/HiburMono"
  commit: "3e0d273f77d243ab80e27ff62a270c57cd119c88"
}
primary_script: "Ethi"
minisite_url: "https://github.com/typehabesha/HiburMono"
stroke: "SANS SERIF"
